### ISSUE TITLE
add current month and week number on top of agenda

### ISSUE THREAD

**Issue by h4m3d66** [hadimostafapour/react-native-calendars-persian#1]
Hi,
is it possible to add current month and week number of month on top of agenda?
for example:
هفته دوم خرداد
هفته اول دی
...

**Comment by hadimostafapour** [comment]
Umm, No there is no way to do this by component itself,
but you can add a listener to `onDayChange` `onDayPress` and get current selected date then simply use moment to format that date and display it before Agenda
```
<Text style={{}}>{this.state.formattedDayOfWeek}</Text>
<Agenda
 {...}
/> 
```
