### ISSUE TITLE
agenda swipe left and right

### ISSUE THREAD

**Issue by FatemeMirzaeii** [hadimostafapour/react-native-calendars-persian#10]
Hi!
do we have any feature to swipe agenda left and right?

**Comment by hadimostafapour** [comment]
This repo became too old as you can see the last commit pushed about 2 years ago. I saw recently the main repository added a `enableSwipeMonths` prop, Please try it and if it's working, just tell me. I will update this repo ASAP (Maybe).

**Comment by FatemeMirzaeii** [comment]
this is not exactly what I want, but it would be nice if we have this feature too!

**Comment by FatemeMirzaeii** [comment]
there are more other features added in the main repo, is it possible to completely update this repo with main and merge them all?

**Comment by hadimostafapour** [comment]
@FatemeMirzaeii Yes, but at the moment I'm so busy. It takes too long to I do update this repo.

**Comment by FatemeMirzaeii** [comment]
thank you, I will do it myself and if you have any advice I will appreciate!
