### ISSUE TITLE
the direction of ArrowLeft and ArrowRight icons are reversed

### ISSUE THREAD

**Issue by safuraalipour** [hadimostafapour/react-native-calendars-persian#11]
<img width="246" alt="Screenshot_1601364173" src="https://user-images.githubusercontent.com/25703556/94526186-0763a500-0242-11eb-95f4-8a647ed056b4.png">

**Comment by hadimostafapour** [comment]
Your app is __LTR__, you have to make app __RTL__ using  `I18nManager.forceRTL(true);`
