### ISSUE TITLE
all days not rendred sometimes

### ISSUE THREAD

**Issue by h4m3d66** [hadimostafapour/react-native-calendars-persian#2]
Hi,
somtimes all days not rendered:
![first](https://user-images.githubusercontent.com/15716660/44270239-28c4cb00-a24c-11e8-8f8d-980f9fbc009f.png)
![second](https://user-images.githubusercontent.com/15716660/44270250-30846f80-a24c-11e8-9632-ff3d8edefd7c.png)

**Comment by h4m3d66** [comment]
This is my Agenda code and it sometimes not rendering all days without any change:
`
<Agenda
          jalali
          firstDay={6}
          // the list of items that have to be displayed in agenda. If you want to render item as empty date
          // the value of date key kas to be an empty array []. If there exists no value for date key it is
          // considered that the date in question is not yet loaded
          items={this.props.userPrograms}
          //   // callback that gets called when items for a certain month should be loaded (month became visible)
          //   loadItemsForMonth={month => {
          //     console.log("trigger items loading");
          //   }}
          // callback that fires when the calendar is opened or closed
          onCalendarToggled={calendarOpened => {
            console.log(calendarOpened);
          }}
          // callback that gets called on day press
          onDayPress={day => {
            const selectedDate = moment(day.dateString).format("YYYY-MM-DD");
            this.setState({
              selectedDate,
              selectedMonth: moment(selectedDate).format("jMMMM"),
              selectedWeek: Math.ceil(moment(selectedDate).format("jDD") / 7)
            });
          }}
          // callback that gets called when day changes while scrolling agenda list
          onDayChange={day => {
            console.log("day changed");
          }}
          //   // initially selected day
          //   selected={"2018-05-16"}
          //   // Minimum date that can be selected, dates before minDate will be grayed out. Default = undefined
          //   minDate={"2018-05-10"}
          //   // Maximum date that can be selected, dates after maxDate will be grayed out. Default = undefined
          //   maxDate={"2018-05-30"}
          // Max amount of months allowed to scroll to the past. Default = 50
          pastScrollRange={50}
          // Max amount of months allowed to scroll to the future. Default = 50
          futureScrollRange={50}
          // specify how each item should be rendered in agenda
          renderItem={(item, firstItemInDay) => {
            return (
              <View style={[styles.item, { height: 120 }]}>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "space-between"
                  }}
                >
                  <View>
                    <Text style={{ color: "gray", fontSize: 10 }}>
                      از
                      {item.StartTime &&
                        moment(item.StartTime).format(" HH:mm A")}
                    </Text>
                    <Text style={{ color: "gray", fontSize: 10 }}>
                      تا
                      {item.EndTime && moment(item.EndTime).format(" HH:mm A")}
                    </Text>
                  </View>
                  <Text style={{ flex: 1, textAlign: "right" }}>
                    {item.Description.length > 30
                      ? item.Description.substr(0, 30) + "..."
                      : item.Description}
                  </Text>

                  <View
                    style={{
                      width: 30,
                      height: 30,
                      marginLeft: 5,
                      backgroundColor: "#" + item.ColorCode,
                      alignItems: "center",
                      justifyContent: "center"
                    }}
                  >
                    <Image
                      style={{
                        width: 20,
                        height: 20
                      }}
                      source={{
                        uri: "http://www.parsehadmin.ir" + item.Icon
                      }}
                    />
                  </View>
                </View>
                <Text style={{ color: "gray", fontSize: 12 }}>
                  {item.Address}
                </Text>
                <View
                  style={{
                    flexDirection: "row",
                    marginHorizontal: 10,
                    marginTop: 10
                  }}
                >
                  <TouchableOpacity
                    style={{ flex: 1, alignItems: "center" }}
                    onPress={() =>
                      this.setState({ alarmEnabled: !alarmEnabled })
                    }
                  >
                    <Image
                      resizeMode="contain"
                      style={styles.programIcon}
                      source={
                        alarmEnabled
                          ? require("../assets/images/icons/logo-blue-forward.png")
                          : require("../assets/images/icons/logo-blue-forward.png")
                      }
                    />
                  </TouchableOpacity>
                  <TouchableOpacity style={{ flex: 1, alignItems: "center" }}>
                    <Image
                      resizeMode="contain"
                      style={styles.programIcon}
                      source={
                        alarmEnabled
                          ? require("../assets/images/icons/bell-yellow.png")
                          : require("../assets/images/icons/bell-gray.png")
                      }
                    />
                  </TouchableOpacity>
                  <TouchableOpacity style={{ flex: 1, alignItems: "center" }}>
                    <Image
                      resizeMode="contain"
                      style={styles.programIcon}
                      source={
                        alarmEnabled
                          ? require("../assets/images/icons/pin-red.png")
                          : require("../assets/images/icons/pin-red.png")
                      }
                    />
                  </TouchableOpacity>
                  <TouchableOpacity style={{ flex: 1, alignItems: "center" }}>
                    <Image
                      resizeMode="contain"
                      style={styles.programIcon}
                      source={
                        alarmEnabled
                          ? require("../assets/images/icons/alarm-clock.png")
                          : require("../assets/images/icons/alarm-clock.png")
                      }
                    />
                  </TouchableOpacity>
                </View>
              </View>
            );
          }}
          //   // specify how each date should be rendered. day can be undefined if the item is not first in that day.
          //   renderDay={(day, item) => {
          //     return <Text>{JSON.stringify(item)}</Text>;
          //   }}
          // specify how empty date content with no items should be rendered
          renderEmptyDate={() => {
            return <View />;
          }}
          // specify how agenda knob should look like
          renderKnob={() => {
            return <Text>...</Text>;
          }}
          // specify what should be rendered instead of ActivityIndicator
          renderEmptyData={() => {
            return <View />;
          }}
          // specify your item comparison function for increased performance
          rowHasChanged={(r1, r2) => {
            return r1.text !== r2.text;
          }}
          // Hide knob button. Default = false
          hideKnob={false}
          //   // By default, agenda dates are marked if they have at least one item, but you can override this if needed
          //   markedDates={{
          //     "2018-05-23": { selected: true, marked: true },
          //     "2018-05-24": { marked: true },
          //     "2018-05-25": { disabled: true }
          //   }}
          // If provided, a standard RefreshControl will be added for "Pull to Refresh" functionality. Make sure to also set the refreshing prop correctly.
          onRefresh={() => console.log("refreshing...")}
          // Set this true while waiting for new data from a refresh
          refreshing={false}
          // Add a custom RefreshControl component, used to provide pull-to-refresh functionality for the ScrollView.
          refreshControl={null}
          // agenda theme
          theme={{
            agendaDayTextColor: "yellow",
            agendaDayNumColor: "green",
            agendaTodayColor: "red",
            agendaKnobColor: "blue",
            selectedDayBackgroundColor: "#940347"
          }}
          // agenda container style
          style={{}}
        />
`

**Comment by hadimostafapour** [comment]
@h4m3d66 which platform? ios/android/both?

**Comment by hadimostafapour** [comment]
@h4m3d66 also try new published version ;)

**Comment by h4m3d66** [comment]
I have tested only on android. 
somestimes  also I get this error without any change on previous version:
![cal error](https://user-images.githubusercontent.com/15716660/44728181-0c991780-aaf1-11e8-8d3c-001544e8b610.png)


thank you for new version. I will test it :)

**Comment by hadimostafapour** [comment]
Fine, I think the problem was `persian-date` package, I've been used the new package weeks ago in production and personally don't face with any problems.

**Comment by h4m3d66** [comment]
1.20.3 is the version that I used...

**Comment by iamhaaamed** [comment]
In the new version, selected day can not be changed and I get this warning:
`VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.`

**Comment by hadimostafapour** [comment]
@h4m3d66 Warning is normal, but I can't figure out the selected day issue, could you provide more details?

 Is your main issue resolved? 
> all days not rendred sometimes

**Comment by iamhaaamed** [comment]
my code is the same as the above code, but after I press knob button, the warning appears and nothing working, I can not change selected day, the calendar not closed,...

**Comment by hadimostafapour** [comment]
Um, I don't know exactly, I tested it on both android and iOS (RN 0.56), everything goes fine.
_Decrease `pastScroll` and `featureScroll` values, maybe helpful._
