### ISSUE TITLE
Month name is in Latin

### ISSUE THREAD

**Issue by bbmokhtari** [hadimostafapour/react-native-calendars-persian#4]
I can't seem to be able to change the month name from `Farvardin` to `فروردین`.
<img width="306" alt="Screen Shot 2019-04-19 at 14 00 20" src="https://user-images.githubusercontent.com/35877268/56418219-86ae2480-62ab-11e9-928e-6ff9815f2562.png">

**Comment by SiSa68** [comment]
It shows me completely in Gregorian calendar!!
How could you config it for jalali?

**Comment by hadimostafapour** [comment]
please provide steps to reproduce this case (code/snippet).

**Comment by ahmadi-akbar** [comment]
please check this
https://github.com/ahmadi-akbar/react-native-calendars-persian
![Capture](https://user-images.githubusercontent.com/48069695/58643143-f89a7480-8313-11e9-8948-48ea4dc03586.PNG)

**Comment by fatemehmemar123** [comment]
hi 
how to rtl week?

**Comment by ahmadi-akbar** [comment]
hello
i have added a rtl (right to left) prop.
please check this
https://github.com/ahmadi-akbar/react-native-calendars-persian
![PersianCalendarExample ScreenShot](https://user-images.githubusercontent.com/48069695/59294134-f205e880-8c95-11e9-8ff8-a0b756409294.png)

**Comment by barbodco** [comment]
this solution is not best practice but work fine
add this line in file node_modules/react-native-calendars-persian/src/persian/dateutils.js
moment.loadPersian({dialect: 'persian-modern'})

**Comment by HekmatBeigverdi** [comment]
Thank you  @barbodco it work's properly!!!

**Comment by barbodco** [comment]
Welcome!

**Comment by barbodco** [comment]
> Thank you @barbodco it work's properly!!!

Welcome!

**Comment by MrKarimi9425** [comment]
Thank you very much @barbodco
